project:
  type: website
  output-dir: docs

website:
  title: "Benjamin Kowialiewski"
  search: false
  navbar:
    background: "dark"
    left:
      - href: index.qmd
        text: Home
      - publications.qmd
      - music.qmd
      - href: "documents/Curriculum.Vitae.pdf"
        text: Academic CV
      - href: https://github.com/bkowialiewski
        text: GitHub page

  page-footer:
    border: false
    background: light
    left:
      - text: "<a href = 'mailto:benjamin.kowialiewski@uzh.ch'>benjamin.kowialiewski@uzh.ch</a> <br>"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



